export enum DeliveryEvents {
	DEFAULT_PRODUCT_SUPPLIER_CHANGED = "DEFAULT_PRODUCT_SUPPLIER_CHANGED",
	DELIVERY_COMPLETED = "DELIVERY_COMPLETED",
	DELIVERY_IS_NOT_COMPLETED_ANYMORE = "DELIVERY_IS_NOT_COMPLETED_ANYMORE",
}
