export enum SALE_EVENTS {
	FIRST_SALE_CREATED_FOR_DATE = "FIRST_SALE_CREATED_FOR_DATE ",
	SALE_ARCHIVED = "SALE_ARCHIVED",
	QUANTITY_DECREMENTED = "SALE_QUANTITY_DECREMENTED",
	QUANTITY_INCREMENTED = "SALE_QUANTITY_INCREMENTED",
}
