-- DROP TABLES (reverse dependency order)
DROP TABLE IF EXISTS sales_forecast CASCADE;
DROP TABLE IF EXISTS sales_forecast_entry CASCADE;
DROP TABLE IF EXISTS delivery_item CASCADE;
DROP TABLE IF EXISTS delivery CASCADE;
DROP TABLE IF EXISTS product_supplier CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS sale CASCADE;
DROP TABLE IF EXISTS product_setting CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_category CASCADE;
DROP TABLE IF EXISTS recovery_token CASCADE;
DROP TABLE IF EXISTS account_permission CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;

-- DROP ENUM TYPES
DROP TYPE IF EXISTS delivery_status CASCADE;
DROP TYPE IF EXISTS sale_status CASCADE;
DROP TYPE IF EXISTS safety_stock_calculation_method CASCADE;
DROP TYPE IF EXISTS product_classification CASCADE;
DROP TYPE IF EXISTS account_role CASCADE;
DROP TYPE IF EXISTS outbox_status CASCADE;
